[package]
name = "radarpub"
description = "EdgeFirst Radar Node - Smart Micro DRVEGRD radar publisher for ROS2/Zenoh"
repository = "https://github.com/EdgeFirstAI/radarpub"
license = "Apache-2.0"
version = "1.6.3"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[[bin]]
name = "edgefirst-radarpub"
path = "src/radarpub.rs"
required-features = ["can", "zenoh"]

[[bin]]
name = "drvegrdctl"
path = "src/drvegrdctl.rs"
required-features = ["can"]

# Examples
[[example]]
name = "radar_viewer"
required-features = ["rerun"]

[[example]]
name = "zenoh_viewer"
required-features = ["rerun", "zenoh"]

[lib]
name = "radarpub"
path = "src/lib.rs"

[features]
default = ["tracy", "can", "zenoh"]
can = ["dep:socketcan"]
rerun = ["dep:rerun", "dep:etherparse", "dep:pcarp", "dep:ndarray-npy"]
zenoh = ["dep:zenoh"]
tracy = ["tracing-tracy/enable", "tracy-client/enable"]
profiling = [
    "tracing-tracy/sampling",
    "tracing-tracy/system-tracing",
    "tracy-client/sampling",
    "tracy-client/system-tracing",
]

[dependencies]
clap = { version = "4.6.6", features = ["derive", "env"] }
crc16 = "0.4.0"
dbscan = "0.3.1"
edgefirst-schemas = "4.0.0"
env_logger = "0.11.11"
etherparse = { version = "0.21.0", optional = true }
kanal = { git = "https://github.com/fereidani/kanal", rev = "b6aeab2" }
lapjv = "0.3.0"
libc = "0.2.180"
log = "0.4.34"
nalgebra = "0.35.0"
ndarray = "0.17.2"
ndarray-npy = { version = "0.10.0", optional = true }
num = "0.4.3"
pcarp = { version = "2.0.0", optional = true }
rerun = { version = "0.36.3", optional = true, features = ["clap"] }
serde_json = "1.0.151"
socketcan = { version = "3.6.2", features = ["tokio"], optional = true }
tokio = { version = "1.53.1", features = [
    "rt-multi-thread",
    "net",
    "time",
    "io-std",
    "tracing",
] }
tracing = "0.1.44"
tracing-journald = "0.3.2"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.23"
tracing-tracy = { version = "0.12.0", default-features = false, features = [
    "manual-lifetime",
    "broadcast",
    "ondemand",
    "fibers",
] }
tracy-client = { version = "0.19.0", default-features = false, features = [
    "manual-lifetime",
    "broadcast",
    "ondemand",
    "fibers",
] }
uuid = { version = "1.26.0", features = ["v4"] }
zenoh = { version = "1.10.0", optional = true }

[dev-dependencies]
etherparse = { version = "0.21.0" }
pcarp = { version = "2.0.0" }
