name: Bug Report
description: Report a bug in RadarPub
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      value: |
        1. Start RadarPub with configuration...
        2. Send CAN messages...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages, logs, or screenshots.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: RadarPub Version
      description: What version are you using? (run `radarpub --version`)
      placeholder: v0.2.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you running on?
      options:
        - Maivin (ARM64)
        - Raivin (ARM64)
        - Linux x86_64
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: rust_version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: rustc 1.84.1
    validations:
      required: false

  - type: dropdown
    id: hardware
    attributes:
      label: Radar Hardware
      description: Do you have actual radar hardware or using virtual CAN?
      options:
        - Smart Micro DRVEGRD 169
        - Smart Micro DRVEGRD 174
        - Virtual CAN (vcan) for testing
        - Other radar sensor
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration settings or command-line arguments
      placeholder: |
        radarpub --can-interface can0 --zenoh-mode peer ...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Relevant log output (enable debug logging with RUST_LOG=debug if needed)
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
        - label: I can reproduce this issue consistently
          required: false
        - label: I have logs or error messages to share
          required: false
