name: Feature Request
description: Suggest a new feature for RadarPub
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case are you trying to enable?
      placeholder: I'm trying to... but currently I have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Be as detailed as possible.
      placeholder: RadarPub should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered? Why do you prefer your proposed solution?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of RadarPub does this relate to?
      options:
        - CAN interface / DRVEGRD protocol
        - Radar cube processing
        - Target clustering / tracking
        - Zenoh publishing / ROS2 integration
        - Visualization (rerun)
        - Configuration / CLI
        - Documentation
        - Other / Multiple components
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for your use case?
      options:
        - Critical (blocking my project)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: Use Case Details
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I'm developing an autonomous vehicle system that needs...
    validations:
      required: false

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature and submit a PR
          required: false
        - label: I can help test this feature once implemented
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with RadarPub's scope (radar sensor processing for EdgeFirst)
          required: false
